#!/bin/sh
set -e

FISH_CONFIG_DIR="/root/.config/fish"
DEFAULT_CONFIG_DIR="/opt/fish_config_default"
APP_NAME=${APP_NAME:-laravel-app}
TZ=${TZ:-UTC}

echo "Starting $APP_NAME..."

# Set timezone at runtime
if [ "$TZ" != "UTC" ]; then
    echo "Setting timezone to $TZ"
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime
    echo $TZ > /etc/timezone
fi

# Make sure the app directory exists
mkdir -p /var/www/html

# Sitemap and robots.txt are generated by Laravel and must not persist as static files.
rm -f /var/www/html/public/sitemap.xml \
    /var/www/html/public/robots.txt \
    /var/www/html/public/sitemap-*.xml

# If the config directory is mounted but uninitialized (i.e., fisher is missing),
# copy the default config from the image into the volume.
if [ ! -f "$FISH_CONFIG_DIR/functions/fisher.fish" ]; then
   echo "Initializing fish config in $FISH_CONFIG_DIR..."
   # Ensure the target functions directory exists before copying
   mkdir -p "$FISH_CONFIG_DIR/functions"

   # Check if default config exists before copying
   if [ -d "$DEFAULT_CONFIG_DIR" ] && [ "$(ls -A $DEFAULT_CONFIG_DIR)" ]; then
      cp -a "$DEFAULT_CONFIG_DIR/." "$FISH_CONFIG_DIR/"
   else
      echo "Warning: Default fish configuration not found in $DEFAULT_CONFIG_DIR"
      # Create a minimal fish config if the default one doesn't exist
      echo "# Basic fish configuration for Laravel" > "$FISH_CONFIG_DIR/config.fish"
      echo "# Add Laravel artisan alias" >> "$FISH_CONFIG_DIR/config.fish"
      echo "alias artisan='php artisan'" >> "$FISH_CONFIG_DIR/config.fish"
      echo "alias tinker='php artisan tinker'" >> "$FISH_CONFIG_DIR/config.fish"
      echo "alias migrate='php artisan migrate'" >> "$FISH_CONFIG_DIR/config.fish"
   fi
fi

# Set working directory
cd /var/www/html

# Ensure Laravel writable directories exist and have correct permissions
mkdir -p storage bootstrap/cache

# Proactively clear potentially stale Laravel caches (especially package discovery)
# This avoids boot errors from stale files persisted via mounted volumes.
if [ -d bootstrap/cache ]; then
    echo "Clearing stale Laravel cache files in bootstrap/cache..."
    rm -f \
        bootstrap/cache/packages.php \
        bootstrap/cache/config.php \
        bootstrap/cache/services.php \
        bootstrap/cache/events.php \
        bootstrap/cache/routes*.php || true
fi

# Initialize/sync built assets into mounted volumes only when the image changed.
ASSET_VERSION_FILE=/opt/built/assets.sha256
ASSET_MARKER=bootstrap/cache/.assets-version

if [ -f "$ASSET_VERSION_FILE" ] && [ -f "$ASSET_MARKER" ] \
    && [ "$(cat "$ASSET_VERSION_FILE")" = "$(cat "$ASSET_MARKER")" ]; then
    echo "Built assets are already synchronized."
else
    echo "Synchronizing built assets into mounted volumes..."

    if [ -d /opt/built/public/build ]; then
        mkdir -p /var/www/html/public/build
        if [ "$APP_ENV" = "production" ]; then rm -rf /var/www/html/public/build/*; fi
        cp -a /opt/built/public/build/. /var/www/html/public/build/
    fi

    if [ -d /opt/built/public/img ]; then
        mkdir -p /var/www/html/public/img
        if [ "$APP_ENV" = "production" ]; then rm -rf /var/www/html/public/img/*; fi
        cp -a /opt/built/public/img/. /var/www/html/public/img/
    fi

    if [ -d /opt/built/public/pl ]; then
        mkdir -p /var/www/html/public/pl
        if [ "$APP_ENV" = "production" ]; then rm -rf /var/www/html/public/pl/*; fi
        cp -a /opt/built/public/pl/. /var/www/html/public/pl/
    fi

    if [ -d /opt/built/public/en ]; then
        mkdir -p /var/www/html/public/en
        if [ "$APP_ENV" = "production" ]; then rm -rf /var/www/html/public/en/*; fi
        cp -a /opt/built/public/en/. /var/www/html/public/en/
    fi

    if [ -d /opt/built/public ]; then
        find /opt/built/public -maxdepth 1 -type f -exec cp -p {} /var/www/html/public/ \;
    fi

    if [ -d /opt/built/bootstrap/ssr ]; then
        mkdir -p /var/www/html/bootstrap/ssr
        if [ "$APP_ENV" = "production" ]; then rm -rf /var/www/html/bootstrap/ssr/*; fi
        cp -a /opt/built/bootstrap/ssr/. /var/www/html/bootstrap/ssr/
    fi

    if [ -f "$ASSET_VERSION_FILE" ]; then
        cp "$ASSET_VERSION_FILE" "$ASSET_MARKER.tmp"
        mv "$ASSET_MARKER.tmp" "$ASSET_MARKER"
    fi
fi

# If running as root, fix ownership and permissions on mounted volumes
if [ "$(id -u)" = "0" ]; then
    echo "Fixing permissions..."
    find storage bootstrap/cache ! -user www-data -exec chown www-data:www-data {} +
    find storage bootstrap/cache -type d ! -perm -g+rwx -exec chmod g+rwx {} +
    find storage bootstrap/cache -type f ! -perm -g+rw -exec chmod g+rw {} +
fi

# Laravel-specific initialization for production
if [ "$APP_ENV" = "production" ]; then
    echo "Production environment detected, waiting for database (for artisan readiness checks)..."

    # Wait for database to be ready (non-fatal loop)
    if command -v php >/dev/null 2>&1; then
        echo "Waiting for database connection..."
        i=1
        while [ $i -le 30 ]; do
            if php artisan migrate:status >/dev/null 2>&1; then
                echo "Database reachable."; break
            fi
            echo "Database not ready, retry $i/30..."
            sleep 5
            i=$((i+1))
        done
    fi
fi

echo "Working in Laravel directory: /var/www/html"

# Execute the command passed to the container
exec "$@"
