services:
  app:
    volumes:
      - /srv/laravel-blog/storage:/var/www/html/storage
      - /srv/laravel-blog/bootstrap_cache:/var/www/html/bootstrap/cache

  queue:
    volumes:
      - /srv/laravel-blog/storage:/var/www/html/storage
      - /srv/laravel-blog/bootstrap_cache:/var/www/html/bootstrap/cache
